<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="17145" started-at="2021-01-10T11:20:56Z" finished-at="2021-01-10T11:21:13Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17145" started-at="2021-01-10T11:20:56Z" finished-at="2021-01-10T11:21:13Z">
      <class name="waltonAutomation.AndroidDemoTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:waltonAutomation.AndroidDemoTest@66a3ffec]" name="setUp" is-config="true" duration-ms="8339" started-at="2021-01-10T11:20:56Z" finished-at="2021-01-10T11:21:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="excelVaue()[pri:1, instance:waltonAutomation.AndroidDemoTest@66a3ffec]" name="excelVaue" duration-ms="7557" started-at="2021-01-10T11:21:04Z" finished-at="2021-01-10T11:21:12Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at waltonAutomation.AndroidDemoTest.excelVaue(AndroidDemoTest.java:121)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- excelVaue -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:waltonAutomation.AndroidDemoTest@66a3ffec]" name="tearDown" is-config="true" duration-ms="1229" started-at="2021-01-10T11:21:12Z" finished-at="2021-01-10T11:21:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- waltonAutomation.AndroidDemoTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
